let allSacra = {
    baptisim: {
        name: 'Baptisim',
        pic: "https://wp.en.aleteia.org/wp-content/uploads/sites/2/2020/01/web3-baptism-baby-newborn-water-bless-shutterstock_1231164460.jpg?quality=100&strip=all",
    txt: 'sed eirmod labore ut amet erat magna, lorem et dolore duo magna dolore, diam lorem justo takimata rebum et sit, et sea takimata voluptua magna, et eirmod amet et amet, consetetur et invidunt sea dolore sit takimata sed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing et. sed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing etsed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing etsed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing etsed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing etsed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing etsed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing etsed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing etsed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing etsed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing et'
    },
    confessionReconsilation: {
        name: 'Confession & Reconsilation',
        pic: "https://wp.en.aleteia.org/wp-content/uploads/sites/2/2020/01/web3-baptism-baby-newborn-water-bless-shutterstock_1231164460.jpg?quality=100&strip=all",
    txt: 'sed eirmod labore ut amet erat magna, lorem et dolore duo magna dolore, diam lorem justo takimata rebum et sit, et sea takimata voluptua magna, et eirmod amet et amet, consetetur et invidunt sea dolore sit takimata sed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing et. sed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing etsed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing etsed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing etsed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing etsed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing etsed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing etsed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing etsed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing etsed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing et'
    },
    confirmation: {
        name: 'Confirmation',
        pic: "https://wp.en.aleteia.org/wp-content/uploads/sites/2/2020/01/web3-baptism-baby-newborn-water-bless-shutterstock_1231164460.jpg?quality=100&strip=all",
    txt: 'sed eirmod labore ut amet erat magna, lorem et dolore duo magna dolore, diam lorem justo takimata rebum et sit, et sea takimata voluptua magna, et eirmod amet et amet, consetetur et invidunt sea dolore sit takimata sed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing et. sed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing etsed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing etsed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing etsed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing etsed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing etsed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing etsed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing etsed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing etsed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing et'
    },
    firstHolyComunnion: {
        name: 'First Holy Comunnion',
        pic: "https://wp.en.aleteia.org/wp-content/uploads/sites/2/2020/01/web3-baptism-baby-newborn-water-bless-shutterstock_1231164460.jpg?quality=100&strip=all",
    txt: 'sed eirmod labore ut amet erat magna, lorem et dolore duo magna dolore, diam lorem justo takimata rebum et sit, et sea takimata voluptua magna, et eirmod amet et amet, consetetur et invidunt sea dolore sit takimata sed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing et. sed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing etsed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing etsed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing etsed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing etsed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing etsed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing etsed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing etsed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing etsed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing et'
    },
    holyOrders: {
        name: 'Holy Orders',
        pic: "https://wp.en.aleteia.org/wp-content/uploads/sites/2/2020/01/web3-baptism-baby-newborn-water-bless-shutterstock_1231164460.jpg?quality=100&strip=all",
    txt: 'sed eirmod labore ut amet erat magna, lorem et dolore duo magna dolore, diam lorem justo takimata rebum et sit, et sea takimata voluptua magna, et eirmod amet et amet, consetetur et invidunt sea dolore sit takimata sed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing et. sed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing etsed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing etsed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing etsed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing etsed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing etsed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing etsed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing etsed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing etsed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing et'
    },
    marriage: {
        name: 'Marriage',
        pic: "https://wp.en.aleteia.org/wp-content/uploads/sites/2/2020/01/web3-baptism-baby-newborn-water-bless-shutterstock_1231164460.jpg?quality=100&strip=all",
    txt: 'sed eirmod labore ut amet erat magna, lorem et dolore duo magna dolore, diam lorem justo takimata rebum et sit, et sea takimata voluptua magna, et eirmod amet et amet, consetetur et invidunt sea dolore sit takimata sed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing et. sed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing etsed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing etsed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing etsed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing etsed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing etsed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing etsed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing etsed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing etsed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing et'
    },
    anointingoftheSick: {
        name: 'Anointing of the Sick',
        pic: "https://wp.en.aleteia.org/wp-content/uploads/sites/2/2020/01/web3-baptism-baby-newborn-water-bless-shutterstock_1231164460.jpg?quality=100&strip=all",
    txt: 'sed eirmod labore ut amet erat magna, lorem et dolore duo magna dolore, diam lorem justo takimata rebum et sit, et sea takimata voluptua magna, et eirmod amet et amet, consetetur et invidunt sea dolore sit takimata sed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing et. sed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing etsed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing etsed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing etsed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing etsed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing etsed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing etsed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing etsed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing etsed justo et, sea elitr clita takimata voluptua stet sanctus sadipscing est et, voluptua rebum tempor consetetur no et. Gubergren gubergren et amet vero voluptua dolor no. Lorem ipsum sadipscing et'
    },
    
}

export default allSacra;